import {useEffect,useRef,useState} from 'react';
import '../houses-guide.css';
export function ContextHelp({topic,experience,onSeen}){
 const [dismissed,setDismissed]=useState(false);
 const content={mega_boost:['🔥 MEGA BOOST','Uma previsão em destaque, que pode ter odds especiais durante tempo limitado. Escolhe a tua opção e aposta com o mesmo saldo de TIPS.'],flash_mission:['⚡ MISSÃO RELÂMPAGO','Aparece sem aviso e dura pouco. Abre a missão para veres a prova, o prazo e as vagas antes de participares.'],house_ranking:['🏠 A TUA CASA TAMBÉM COMPETE','Os TIPS dos membros elegíveis com conta criada contribuem para a classificação da Casa. A regra atual aparece no ranking.']};
 if(!experience||dismissed||experience.seen_help?.includes(topic))return null;
 return <aside className="fds-context-help"><div><strong>{content[topic][0]}</strong><p>{content[topic][1]}</p></div><button onClick={()=>{setDismissed(true);onSeen?.({help:topic});}}>Percebi ✓</button></aside>;
}
function GuideContent({step,name,houseNumber}){
 if(step===0)return <><span className="guide-symbol">👑</span><p className="guide-eyebrow">BEM-VINDO AO</p><h1>NOVA <em>TIPS</em></h1><h2>O FDS também se joga.</h2><p>Faz previsões, completa missões, ganha TIPS e tenta chegar ao topo — sozinho e com a tua Casa.</p><div className="guide-pills"><span>🔮 Prevê</span><span>🔥 Participa</span><span>🏆 Compete</span></div></>;
 if(step===1)return <><span className="guide-symbol">🔮</span><h1>PREVÊ O <em>FDS</em></h1><p>Usa os teus TIPS para prever o que vai acontecer.</p><div className="guide-example"><span>100 TIPS<small>A tua previsão · odd 2.00</small></span><b>→</b><span>200 TIPS<small>Retorno se acertares</small></span></div><small>O retorno inclui os 100 TIPS usados. Se falhares, perdes esses 100 TIPS.</small><div className="guide-mini"><strong>🔥 MEGA BOOST</strong><p>Previsões em destaque, algumas com odds especiais, durante tempo limitado.</p></div></>;
 if(step===2)return <><span className="guide-symbol">🔥</span><h1>COMPLETA <em>MISSÕES</em></h1><h2>Não é só prever.</h2><p>Completa desafios durante o FDS e ganha TIPS extra.</p><ol className="guide-steps"><li>📸 Faz o desafio</li><li>📲 Envia a prova indicada na missão</li><li>✓ A equipa valida ou escolhe os vencedores</li><li>🪙 Recebe a recompensa, conforme as regras</li></ol><p>⚡ Algumas missões aparecem sem aviso. Fica atento!</p></>;
 return <><span className="guide-symbol">🏆</span><h1>SOBE NO <em>RANKING</em></h1><h2>Compete sozinho. Ajuda a tua Casa.</h2><div className="guide-ranking-example"><div><span>👤 INDIVIDUAL</span><strong>{name||'Tu'}</strong><small>O teu saldo, os teus acertos</small></div><div><span>🏠 A TUA CASA</span><strong>{houseNumber?'Casa '+houseNumber:'Ainda não atribuída'}</strong><small>Os membros contribuem com o mesmo saldo</small></div></div><p>Todos os TIPS entram no mesmo saldo. Cada TIPS conta.</p></>;
}
export function Onboarding({name,houseNumber,onClose}){
 const [step,setStep]=useState(0);const dialog=useRef(null);
 useEffect(()=>{const previous=document.activeElement;dialog.current?.focus();function key(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const focusable=[...dialog.current.querySelectorAll('button')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[onClose]);
 return <div className="guide-overlay"><section className="guide-onboarding" role="dialog" aria-modal="true" aria-label="Bem-vindo ao NOVA TIPS" ref={dialog} tabIndex={-1}><header><span>{step+1} / 4</span><button onClick={onClose}>Saltar</button></header><div className="guide-slide" aria-live="polite"><GuideContent step={step} name={name} houseNumber={houseNumber}/></div><div className="guide-progress" aria-label={'Passo '+(step+1)+' de 4'}>{[0,1,2,3].map(i=><span key={i} className={i===step?'active':''}/>)}</div><footer><button disabled={step===0} onClick={()=>setStep(step-1)}>← Voltar</button><button className="guide-primary" onClick={()=>step===3?onClose():setStep(step+1)}>{step===0?'Começar →':step===3?'🔥 Entrar no NOVA TIPS':'Seguinte →'}</button></footer><small className="guide-disclaimer">TIPS 100% virtuais · Sem dinheiro real · Apenas entretenimento</small></section></div>;
}
export default function FdsGuide({name,houseNumber,onReplay,onNavigate}){
 return <main className="fds-guide-page"><header className="guide-page-hero"><p className="guide-eyebrow">O FDS TAMBÉM SE JOGA</p><h1>COMO <em>FUNCIONA</em></h1><p>Prevê. Participa. Compete. Representa a tua Casa.</p><button className="guide-primary" onClick={onReplay}>👑 Rever apresentação</button></header><div className="guide-page-grid">{[1,2,3].map(step=><section className="guide-panel" key={step}><GuideContent step={step} name={name} houseNumber={houseNumber}/>{step===1?<button onClick={()=>onNavigate('bets')}>Ver previsões →</button>:step===2?<button onClick={()=>onNavigate('missions')}>Ver missões →</button>:<button onClick={()=>onNavigate('leaderboard')}>Ver classificações →</button>}</section>)}<section className="guide-panel"><span className="guide-symbol">🏠</span><h2>DEFENDE A TUA CASA</h2><p>A tua Casa é atribuída pela lista oficial. Podes vê-la no perfil. Se estiver em falta ou incorreta, pede à organização para corrigir.</p><p>O ranking das casas usa o saldo real dos membros elegíveis. A média por membro é a regra inicial; o ranking mostra sempre a regra em uso.</p><button onClick={()=>onNavigate('leaderboard')}>Batalha das Casas →</button></section></div></main>;
}
