import {useCallback,useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import AdminUserSearch from './AdminUserSearch';
import {formatHouseScore,houseImportStates,summarizeHouseImport} from '../lib/houses';
import '../houses-guide.css';
export default function HousesAdmin(){
 const [houses,setHouses]=useState([]),[users,setUsers]=useState([]),[pending,setPending]=useState([]),[selectedHouse,setSelectedHouse]=useState('all'),[selectedUser,setSelectedUser]=useState(null),[newHouse,setNewHouse]=useState(''),[mode,setMode]=useState('average'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[rows,setRows]=useState(null),[preview,setPreview]=useState(null),[importId,setImportId]=useState(null),[importApplied,setImportApplied]=useState(false);
 const houseDialog=useRef(null),houseSelect=useRef(null);const [editError,setEditError]=useState(''),[savedUserId,setSavedUserId]=useState(null);
 useEffect(()=>{if(!selectedUser)return;const previous=document.activeElement;houseSelect.current?.focus();const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';function key(event){if(event.key==='Escape'&&!busy)setSelectedUser(null);if(event.key==='Tab'){const controls=[...houseDialog.current.querySelectorAll('button:not(:disabled),select:not(:disabled)')];const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',key);previous?.focus();};},[selectedUser,busy]);
 async function saveHouse(event){event.preventDefault();if(busy)return;setBusy(true);setEditError('');try{const {error}=await supabase.rpc('admin_set_user_house',{p_user_id:selectedUser.id,p_house_id:newHouse||null});if(error)throw error;await load();setSavedUserId(selectedUser.id);setSelectedUser(null);setNotice('Casa guardada no Supabase.');}catch(error){setEditError(error.message);}finally{setBusy(false);}}
 const load=useCallback(async()=>{const [h,u,p]=await Promise.all([supabase.rpc('fds_house_leaderboard'),supabase.rpc('admin_fds_house_users'),supabase.rpc('admin_fds_pending_roster')]);if(h.error||u.error||p.error)throw h.error||u.error||p.error;setHouses(h.data||[]);setUsers(u.data||[]);setPending(p.data||[]);setMode(h.data?.[0]?.ranking_mode||'average');},[]);
 useEffect(()=>{let active=true;Promise.resolve().then(()=>{if(active)return load();}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[load]);
 async function action(run,message){if(busy)return;setBusy(true);setError('');setNotice('');try{await run();await load();setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function edit(user){const actual=users.find(u=>u.id===user.id)||user;setSelectedUser(actual);setNewHouse(actual.house_id||'');setNotice('');setEditError('');}
 async function file(event){setError('');setPreview(null);setImportId(null);setImportApplied(false);setRows(null);const selected=event.target.files[0];if(!selected)return;try{if(selected.size>2000000)throw new Error('O ficheiro é demasiado grande.');const parsed=JSON.parse(await selected.text());if(!Array.isArray(parsed))throw new Error('Escolhe o ficheiro JSON de correspondências oficiais.');setRows(parsed);}catch(e){setError(e.message);}}
 async function prepare(){if(busy||!rows)return;setBusy(true);setError('');try{const id=crypto.randomUUID();const {data,error}=await supabase.rpc('prepare_fds_house_import',{p_request_id:id,p_rows:rows});if(error)throw error;setPreview(data);setImportId(id);setImportApplied(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const shown=users.filter(u=>selectedHouse==='all'||selectedHouse==='none'&&!u.house_id||u.house_id===selectedHouse),counts=preview?summarizeHouseImport(preview):{};
 return <div className="missions-admin houses-admin"><header><div><h1>🏠 Casas FDS</h1><p>Atribuições oficiais, correções simples e uma competição ligada ao saldo real.</p></div></header>{error&&<p className="editor-error" role="alert">{error}</p>}{notice&&<p className="editor-notice" role="status">{notice}</p>}
 {users.length>0&&users.every(u=>!u.house_id)&&pending.length===0&&<aside className="house-setup-notice"><strong>A estrutura das casas está criada, mas a lista oficial ainda não foi carregada.</strong><p>Executa o ficheiro seed-fds-houses.sql no SQL Editor do Supabase FDS e depois toca em Atualizar dados. As casas serão ligadas às contas pelo número de aluno.</p><button disabled={busy} onClick={()=>action(async()=>{},'Dados atualizados.')}>Atualizar dados</button></aside>}
 <div className="house-admin-stats"><span><b>{houses.length}</b> casas</span><span><b>{users.filter(u=>u.eligible).length}</b> contas elegíveis</span><button onClick={()=>setSelectedHouse('none')}><b>{users.filter(u=>!u.house_id).length}</b> contas sem casa · Resolver →</button><span><b>{pending.length}</b> atribuições à espera de conta</span></div>
 <section className="editor-panel"><h2>Regra da Batalha das Casas</h2><p>Usa os mesmos membros elegíveis dos bónus de TIPS. Empates exatos partilham posição.</p><form className="house-inline-form" onSubmit={e=>{e.preventDefault();action(async()=>{const {error}=await supabase.rpc('admin_set_house_ranking',{p_mode:mode});if(error)throw error;},'Regra de classificação guardada.');}}><label>Classificar por<select value={mode} onChange={e=>setMode(e.target.value)}><option value="average">Média de TIPS por membro</option><option value="total">Total de TIPS</option></select></label><button disabled={busy} className="editor-primary">Guardar regra</button></form></section>
 <section className="editor-panel"><h2>Procurar e corrigir utilizador</h2><AdminUserSearch rpc="search_fds_house_users" onSelect={edit} disabled={busy}/></section>
 <div className="house-admin-cards">{[...houses].sort((a,b)=>a.number-b.number).map(h=><button key={h.id} aria-pressed={selectedHouse===h.id} onClick={()=>setSelectedHouse(h.id)}><span>🏠 {h.display_name}</span><b>{users.filter(u=>u.house_id===h.id).length+pending.filter(p=>p.house_number===h.number).length} membros · {users.filter(u=>u.house_id===h.id).length} contas</b><small>{formatHouseScore(h.total_tips)} TIPS · {formatHouseScore(h.average_tips)} média{h.rank?' · #'+h.rank:''}</small></button>)}</div>
 <section className="editor-panel"><div className="ranking-list-heading"><h2>{selectedHouse==='none'?'⚠ Utilizadores sem casa':selectedHouse==='all'?'Todos os utilizadores':houses.find(h=>h.id===selectedHouse)?.display_name}</h2><button onClick={()=>setSelectedHouse('all')}>Ver todos</button></div>{shown.map(u=><div className="mission-participant" key={u.id}><div><strong>{u.username||u.official_name||u.student_number}</strong><small>{u.student_number} · {u.house_number?'Casa '+u.house_number:'Sem casa'}{!u.eligible?' · Excluído do ranking das casas':''}</small>{savedUserId===u.id&&<small role="status" className="house-save-confirmation">✓ Casa guardada no Supabase</small>}</div><button disabled={busy} onClick={()=>edit(u)}>Alterar casa</button></div>)}{selectedHouse!=='none'&&pending.filter(p=>selectedHouse==='all'||p.house_number===houses.find(h=>h.id===selectedHouse)?.number).map(p=><div className="mission-participant" key={p.student_number}><div><strong>{p.official_name}</strong><small>{p.student_number} · Casa {p.house_number} · Conta ainda não criada</small></div></div>)}{!shown.length&&<p>Sem contas nesta seleção.</p>}</section>
 <details className="editor-panel house-import-advanced"><summary>Atualizar lista oficial (avançado)</summary><p>Serve apenas para carregar uma lista nova de alunos e casas. Depois de preencher a tabela no Supabase, não precisas de usar esta opção para gerir ou guardar alterações.</p><input aria-label="Lista oficial de casas" type="file" accept=".json,application/json" onChange={file} disabled={busy}/>{rows&&<button disabled={busy} onClick={prepare}>Pré-visualizar {rows.length} participantes →</button>}{preview&&<><div className="house-import-counts">{Object.entries(counts).map(([status,n])=><span key={status}><b>{n}</b> {houseImportStates[status]}</span>)}</div><div className="house-import-report">{preview.map((r,i)=><div key={i} className={'import-'+r.status}><strong>{r.name}</strong><span>{r.student_number||'Sem número confirmado'} · Casa {r.house_number}</span><small>{houseImportStates[r.status]}{r.candidates?.length?' · Candidatos: '+r.candidates.join(' / '):''}</small></div>)}</div><p>Os conflitos e nomes por resolver ficam de fora. As atribuições confirmadas sem conta ficam guardadas para o futuro registo.</p><button className="editor-primary" disabled={busy||importApplied||!(counts.matched||counts.pending_account)} onClick={()=>action(async()=>{const {error}=await supabase.rpc('apply_fds_house_import',{p_request_id:importId});if(error)throw error;setImportApplied(true);},'Importação aplicada. As entradas por resolver não foram atribuídas.')}>{importApplied?'✓ Importação aplicada':'Confirmar importação das correspondências seguras'}</button></>}
 </details>{pending.length>0&&<section className="editor-panel"><h2>À espera de conta</h2><p>Estas atribuições já estão guardadas no Supabase. A casa será associada automaticamente quando a pessoa criar conta.</p>{pending.map(p=><div className="house-member" key={p.student_number}><span>{p.official_name} · {p.student_number}</span><strong>{p.house_number?'Casa '+p.house_number:'Sem casa'}</strong></div>)}</section>}{selectedUser&&<div className="house-edit-overlay"><section className="house-edit-dialog" role="dialog" aria-modal="true" aria-labelledby="house-edit-title" ref={houseDialog}><h2 id="house-edit-title">Alterar casa</h2><p><strong>{selectedUser.username||selectedUser.official_name||selectedUser.student_number}</strong><br/>Nº aluno: {selectedUser.student_number}</p><form onSubmit={saveHouse}><label>Casa<select ref={houseSelect} aria-label="Casa do utilizador" value={newHouse} disabled={busy} onChange={e=>setNewHouse(e.target.value)}><option value="">Sem casa</option>{[...houses].sort((a,b)=>a.number-b.number).map(h=><option key={h.id} value={h.id}>{h.display_name}</option>)}</select></label><small>A alteração fica guardada no Supabase e mantém-se depois de atualizar a página.</small>{editError&&<p className="editor-error" role="alert">{editError}</p>}<footer><button type="button" disabled={busy} onClick={()=>setSelectedUser(null)}>Cancelar</button><button disabled={busy} className="editor-primary">{busy?'A guardar…':'Guardar casa'}</button></footer></form></section></div>}</div>;
}
