import {useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import AdminUserSearch from './AdminUserSearch';
import {formatHouseScore,houseImportStates,summarizeHouseImport} from '../lib/houses';
import '../houses-guide.css';
export default function HousesAdmin(){
 const [houses,setHouses]=useState([]),[users,setUsers]=useState([]),[pending,setPending]=useState([]),[selectedHouse,setSelectedHouse]=useState('all'),[selectedUser,setSelectedUser]=useState(null),[newHouse,setNewHouse]=useState(''),[mode,setMode]=useState('average'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[rows,setRows]=useState(null),[preview,setPreview]=useState(null),[importId,setImportId]=useState(null),[importApplied,setImportApplied]=useState(false);
 const load=useCallback(async()=>{const [h,u,p]=await Promise.all([supabase.rpc('fds_house_leaderboard'),supabase.rpc('admin_fds_house_users'),supabase.rpc('admin_fds_pending_roster')]);if(h.error||u.error||p.error)throw h.error||u.error||p.error;setHouses(h.data||[]);setUsers(u.data||[]);setPending(p.data||[]);setMode(h.data?.[0]?.ranking_mode||'average');},[]);
 useEffect(()=>{let active=true;Promise.resolve().then(()=>{if(active)return load();}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[load]);
 async function action(run,message){if(busy)return;setBusy(true);setError('');setNotice('');try{await run();await load();setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function edit(user){const actual=users.find(u=>u.id===user.id)||user;setSelectedUser(actual);setNewHouse(actual.house_id||'');setNotice('');}
 async function file(event){setError('');setPreview(null);setImportId(null);setImportApplied(false);setRows(null);const selected=event.target.files[0];if(!selected)return;try{if(selected.size>2000000)throw new Error('O ficheiro é demasiado grande.');const parsed=JSON.parse(await selected.text());if(!Array.isArray(parsed))throw new Error('Escolhe o ficheiro JSON de correspondências oficiais.');setRows(parsed);}catch(e){setError(e.message);}}
 async function prepare(){if(busy||!rows)return;setBusy(true);setError('');try{const id=crypto.randomUUID();const {data,error}=await supabase.rpc('prepare_fds_house_import',{p_request_id:id,p_rows:rows});if(error)throw error;setPreview(data);setImportId(id);setImportApplied(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const shown=users.filter(u=>selectedHouse==='all'||selectedHouse==='none'&&!u.house_id||u.house_id===selectedHouse),counts=preview?summarizeHouseImport(preview):{};
 return <div className="missions-admin houses-admin"><header><div><h1>🏠 Casas FDS</h1><p>Atribuições oficiais, correções simples e uma competição ligada ao saldo real.</p></div></header>{error&&<p className="editor-error" role="alert">{error}</p>}{notice&&<p className="editor-notice" role="status">{notice}</p>}
 <div className="house-admin-stats"><span><b>{houses.length}</b> casas</span><span><b>{users.filter(u=>u.eligible).length}</b> contas elegíveis</span><button onClick={()=>setSelectedHouse('none')}><b>{users.filter(u=>!u.house_id).length}</b> contas sem casa · Resolver →</button><span><b>{pending.length}</b> atribuições à espera de conta</span></div>
 <section className="editor-panel"><h2>Regra da Batalha das Casas</h2><p>Usa os mesmos membros elegíveis dos bónus de TIPS. Empates exatos partilham posição.</p><form className="house-inline-form" onSubmit={e=>{e.preventDefault();action(async()=>{const {error}=await supabase.rpc('admin_set_house_ranking',{p_mode:mode});if(error)throw error;},'Regra de classificação guardada.');}}><label>Classificar por<select value={mode} onChange={e=>setMode(e.target.value)}><option value="average">Média de TIPS por membro</option><option value="total">Total de TIPS</option></select></label><button disabled={busy} className="editor-primary">Guardar regra</button></form></section>
 <section className="editor-panel"><h2>Procurar e corrigir utilizador</h2><AdminUserSearch rpc="search_fds_house_users" onSelect={edit} disabled={busy}/>{selectedUser&&<form className="house-inline-form" onSubmit={e=>{e.preventDefault();action(async()=>{const {error}=await supabase.rpc('admin_set_user_house',{p_user_id:selectedUser.id,p_house_id:newHouse||null});if(error)throw error;setSelectedUser(null);},'Casa guardada. O saldo de TIPS não foi alterado.');}}><strong>{selectedUser.username||selectedUser.student_number}</strong><label>Casa<select aria-label="Casa do utilizador" value={newHouse} onChange={e=>setNewHouse(e.target.value)}><option value="">Sem casa</option>{[...houses].sort((a,b)=>a.number-b.number).map(h=><option key={h.id} value={h.id}>{h.display_name}</option>)}</select></label><button disabled={busy} className="editor-primary">Guardar casa</button><button type="button" onClick={()=>setSelectedUser(null)}>Cancelar</button></form>}</section>
 <div className="house-admin-cards">{[...houses].sort((a,b)=>a.number-b.number).map(h=><button key={h.id} aria-pressed={selectedHouse===h.id} onClick={()=>setSelectedHouse(h.id)}><span>🏠 {h.display_name}</span><b>{users.filter(u=>u.house_id===h.id).length+pending.filter(p=>p.house_number===h.number).length} membros · {users.filter(u=>u.house_id===h.id).length} contas</b><small>{formatHouseScore(h.total_tips)} TIPS · {formatHouseScore(h.average_tips)} média{h.rank?' · #'+h.rank:''}</small></button>)}</div>
 <section className="editor-panel"><div className="ranking-list-heading"><h2>{selectedHouse==='none'?'⚠ Utilizadores sem casa':selectedHouse==='all'?'Todos os utilizadores':houses.find(h=>h.id===selectedHouse)?.display_name}</h2><button onClick={()=>setSelectedHouse('all')}>Ver todos</button></div>{shown.map(u=><div className="mission-participant" key={u.id}><div><strong>{u.username||u.official_name||u.student_number}</strong><small>{u.student_number} · {u.house_number?'Casa '+u.house_number:'Sem casa'}{!u.eligible?' · Excluído do ranking das casas':''}</small></div><button disabled={busy} onClick={()=>edit(u)}>Alterar casa</button></div>)}{selectedHouse!=='none'&&pending.filter(p=>selectedHouse==='all'||p.house_number===houses.find(h=>h.id===selectedHouse)?.number).map(p=><div className="mission-participant" key={p.student_number}><div><strong>{p.official_name}</strong><small>{p.student_number} · Casa {p.house_number} · Conta ainda não criada</small></div></div>)}{!shown.length&&<p>Sem contas nesta seleção.</p>}</section>
 <section className="editor-panel"><h2>Importar lista oficial</h2><p>Carrega o JSON de correspondências. A importação usa números de aluno, preserva correções manuais e apresenta conflitos antes de guardar. Não cria contas nem altera TIPS.</p><input aria-label="Lista oficial de casas" type="file" accept=".json,application/json" onChange={file} disabled={busy}/>{rows&&<button disabled={busy} onClick={prepare}>Pré-visualizar {rows.length} participantes →</button>}{preview&&<><div className="house-import-counts">{Object.entries(counts).map(([status,n])=><span key={status}><b>{n}</b> {houseImportStates[status]}</span>)}</div><div className="house-import-report">{preview.map((r,i)=><div key={i} className={'import-'+r.status}><strong>{r.name}</strong><span>{r.student_number||'Sem número confirmado'} · Casa {r.house_number}</span><small>{houseImportStates[r.status]}{r.candidates?.length?' · Candidatos: '+r.candidates.join(' / '):''}</small></div>)}</div><p>Os conflitos e nomes por resolver ficam de fora. As atribuições confirmadas sem conta ficam guardadas para o futuro registo.</p><button className="editor-primary" disabled={busy||importApplied||!(counts.matched||counts.pending_account)} onClick={()=>action(async()=>{const {error}=await supabase.rpc('apply_fds_house_import',{p_request_id:importId});if(error)throw error;setImportApplied(true);},'Importação aplicada. As entradas por resolver não foram atribuídas.')}>{importApplied?'✓ Importação aplicada':'Confirmar importação das correspondências seguras'}</button></>}
 </section>{pending.length>0&&<section className="editor-panel"><h2>À espera de conta</h2><p>Estas pessoas têm uma atribuição guardada, mas ainda não criaram conta.</p>{pending.map(p=><div className="house-member" key={p.student_number}><span>{p.official_name} · {p.student_number}</span><strong>{p.house_number?'Casa '+p.house_number:'Sem casa'}</strong></div>)}</section>}</div>;
}
