import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {formatHouseScore,houseMetricLabel} from '../lib/houses';
import {ContextHelp} from './FdsGuide';
export default function HouseRanking({user,experience,onSeen}){
 const [houses,setHouses]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[members,setMembers]=useState([]),[detailError,setDetailError]=useState(''),[detailLoading,setDetailLoading]=useState(false);
 useEffect(()=>{let active=true;async function load(){const {data,error}=await supabase.rpc('fds_house_leaderboard');if(active){setError(error?'Não foi possível carregar as casas. Se esta opção acabou de ser adicionada, a organização precisa de ativá-la.':'');if(!error)setHouses(data||[]);setLoading(false);}}load();const timer=setInterval(load,30000);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',load);};},[user?.id]);
 useEffect(()=>{if(!selected)return;let active=true;async function load(){setDetailLoading(true);const {data,error}=await supabase.rpc('fds_house_members',{p_house_id:selected});if(active){setMembers(data||[]);setDetailError(error?error.message:'');setDetailLoading(false);}}load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[selected]);
 const mode=houses[0]?.ranking_mode||'average',own=houses.find(h=>h.id===experience?.house_id),top=houses.filter(h=>h.rank!=null).slice(0,3),podium=[top[1],top[0],top[2]].filter(Boolean),detail=houses.find(h=>h.id===selected);
 return <><ContextHelp key={user?.id} topic="house_ranking" experience={experience} onSeen={onSeen}/><section className="ranking-hero house-ranking-hero"><header><h1>🏠 BATALHA DAS <em>CASAS</em></h1><p>Qual Casa está a dominar o FDS?</p></header>{!loading&&!error&&<div className="ranking-podium">{podium.map(h=><button key={h.id} className={'podium-card house-podium podium-'+(top.indexOf(h)+1)} onClick={()=>setSelected(h.id)}><span className="podium-crown" aria-hidden="true">♛</span><span className="podium-rank">#{h.rank}</span><span className="house-emblem">{h.number}</span><h2>{h.display_name}</h2><strong>{formatHouseScore(h.score)}</strong><small className="house-metric">{houseMetricLabel(mode)}</small><p>{formatHouseScore(h.total_tips)} TIPS totais · {h.member_count} membros</p><div className="podium-base"/></button>)}</div>}</section>
 <section className="ranking-own"><div><h2>🏠 A TUA CASA</h2><strong>{own?own.display_name:experience?'Ainda não atribuída':'Entra para veres a tua Casa'}</strong><p>{own?.rank?'#'+own.rank+' no FDS':own?'Ainda sem membros elegíveis com conta':'A organização pode corrigir a tua atribuição.'}</p></div>{own&&<strong className="ranking-balance">{formatHouseScore(own.score)} <small>{houseMetricLabel(mode)}</small></strong>}</section>
 <section className="ranking-list house-ranking-list"><div className="ranking-list-heading"><h2>🏆 CLASSIFICAÇÃO DAS CASAS</h2><span>{mode==='average'?'Por média ↓':'Por total ↓'}</span></div><p className="ranking-ties">{mode==='average'?'Média = TIPS totais ÷ membros elegíveis com conta criada.':'Total = soma dos TIPS dos membros elegíveis com conta criada.'} Empates exatos partilham a posição. Casas sem membros elegíveis ainda não têm posição.</p>{loading?<p role="status">A carregar casas…</p>:error?<p role="alert">{error}</p>:<div className="house-ranking-rows"><div className="house-ranking-row house-ranking-head"><span>#</span><span>CASA</span><span>{houseMetricLabel(mode)}</span><span>MEMBROS</span></div>{houses.map(h=><button key={h.id} className={'house-ranking-row '+(h.id===own?.id?'is-current':'')} onClick={()=>setSelected(h.id)}><span className={'ranking-medal medal-'+h.rank}>{h.rank||'—'}</span><span><strong>{h.display_name}{h.id===own?.id?' · Tu':''}</strong><small>{formatHouseScore(h.total_tips)} TIPS totais</small></span><b>{formatHouseScore(h.score)}</b><span>{h.member_count}</span></button>)}</div>}</section>
 {detail&&<section className="ranking-list house-detail" aria-label={'Membros da '+detail.display_name}><div className="ranking-list-heading"><h2>🏠 {detail.display_name} · {detail.rank?'#'+detail.rank:'Sem posição'}</h2><button onClick={()=>setSelected(null)}>Fechar ✕</button></div><p>{formatHouseScore(detail.score)} {houseMetricLabel(mode)} · {formatHouseScore(detail.total_tips)} TIPS totais · {detail.member_count} membros elegíveis</p>{detailLoading?<p role="status">A carregar membros…</p>:detailError?<p role="alert">{detailError}</p>:members.length?members.map(m=><div className="house-member" key={m.id}><span>{m.username?.trim()||m.student_number}{m.id===user?.id?' · Tu':''}</span><strong>{formatHouseScore(m.balance)} TIPS</strong></div>):<p>Ainda não há membros elegíveis com conta criada nesta Casa.</p>}</section>}</>;
}
