import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {buildWrappedStories} from '../lib/wrappedStories';
import '../wrapped.css';
const fmt=n=>Number(n||0).toLocaleString('pt-PT');
export function WrappedViewer({payload,onClose,onNavigate}){
 const slides=buildWrappedStories(payload),[index,setIndex]=useState(0),[sound,setSound]=useState(false),[audioAvailable,setAudioAvailable]=useState(false);
 const audio=useRef(null),touchX=useRef(null),manualSoundChoice=useRef(false),current=slides[Math.min(index,slides.length-1)];
 useEffect(()=>{let active=true;fetch('/fds/wrapped-theme.mp3',{method:'HEAD'}).then(r=>{if(active&&r.ok&&/audio|mpeg|octet-stream/.test(r.headers.get('content-type')||'')){setAudioAvailable(true);setSound(true);}}).catch(()=>{});return()=>{active=false;};},[]);
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[]);
 useEffect(()=>{const key=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')setIndex(i=>Math.min(slides.length-1,i+1));if(e.key==='ArrowLeft')setIndex(i=>Math.max(0,i-1));};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onClose,slides.length]);
 useEffect(()=>{if(!audio.current)return;if(sound){audio.current.volume=.35;audio.current.play().catch(()=>setSound(false));}else audio.current.pause();},[sound]);
 const startMusic=()=>{if(audioAvailable&&!manualSoundChoice.current&&audio.current?.paused){audio.current.volume=.35;audio.current.play().then(()=>setSound(true)).catch(()=>{});}};
 const toggleSound=()=>{manualSoundChoice.current=true;if(sound){audio.current?.pause();setSound(false);}else audio.current?.play().then(()=>setSound(true)).catch(()=>setSound(false));};
 const next=()=>{startMusic();if(index>=slides.length-1){onClose(true);return;}setIndex(i=>Math.min(slides.length-1,i+1));};
 if(!current)return <div className="wrapped-overlay" role="dialog" aria-modal="true" aria-label="FDS Wrapped"><button className="wrapped-main-action" onClick={()=>onClose()}>Fechar Wrapped</button></div>;
 return <div className="wrapped-overlay" role="dialog" aria-modal="true" aria-label={payload.preview?'Prévia do FDS Wrapped':'FDS Wrapped'}>
 <div className={'wrapped-canvas wrapped-'+current.type} style={{'--wrapped-photo':`url("${current.photo}")`}} onTouchStart={e=>{touchX.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(touchX.current==null)return;const d=e.changedTouches[0].clientX-touchX.current;if(Math.abs(d)>45)setIndex(i=>Math.max(0,Math.min(slides.length-1,i+(d<0?1:-1))));touchX.current=null;}} onClick={e=>{if(e.target.closest('button,a'))return;startMusic();const x=e.clientX-e.currentTarget.getBoundingClientRect().left;setIndex(i=>Math.max(0,Math.min(slides.length-1,i+(x<e.currentTarget.clientWidth*.3?-1:1))));}}>
 <div className="wrapped-progress" aria-label={`História ${index+1} de ${slides.length}`}>{slides.map((s,i)=><span key={s.id} className={i<=index?'filled':''}/>)}</div>
 <div className="wrapped-top"><strong>NOVA <em>TIPS</em></strong>{payload.preview&&<b className="wrapped-preview-tag">PRÉVIA · dados provisórios</b>}<div><button onClick={toggleSound} disabled={!audioAvailable} title={audioAvailable?'Ligar ou desligar música':'Música ainda indisponível'}>{sound?'♫':'♪'}</button><button onClick={()=>onClose()} aria-label="Fechar Wrapped">×</button></div></div>
 <div className="wrapped-story" key={current.id}><p className="wrapped-eyebrow">{current.eyebrow}</p>{current.type==='podium'?<div className="wrapped-house-list">{current.houses.map(h=><div key={h.number}><b>#{h.rank} CASA {h.number}</b><strong>{fmt(h.score)}</strong><small>{h.rank===1?'👑 ':''}{current.body}</small></div>)}</div>:<>{current.title&&<h2>{current.title}</h2>}{current.number&&<strong className="wrapped-huge">{current.number}</strong>}{current.unit&&<h3>{current.unit}</h3>}{current.body&&<p className="wrapped-body">{current.body}</p>}</>}</div>
 <div className="wrapped-bottom">{current.type==='ending'?<button className="wrapped-main-action" onClick={()=>{onClose(true);onNavigate?.(payload.kind==='day1'?'bets':'leaderboard');}}>{payload.kind==='day1'?'VER APOSTAS →':'VER CLASSIFICAÇÃO →'}</button>:<button className="wrapped-continue" onClick={e=>{e.stopPropagation();next();}}>TOCA PARA CONTINUAR →</button>}</div>
 </div>{audioAvailable&&<audio ref={audio} src="/fds/wrapped-theme.mp3" loop preload="auto"/>}</div>;
}
export default function WrappedExperience({user,onNavigate,showEntry=true}){
 const [available,setAvailable]=useState([]),[loadedFor,setLoadedFor]=useState(null),[payload,setPayload]=useState(null),[announce,setAnnounce]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!user)return;let active=true;async function load(){const {data,error}=await supabase.rpc('fds_wrapped_status');if(!active||error)return;setAvailable(data||[]);setLoadedFor(user.id);const unseen=(data||[]).find(v=>!v.announcement_seen);if(unseen)setAnnounce(unseen.kind);}load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[user]);
 const mark=async(kind,action)=>{await supabase.rpc('fds_wrapped_mark',{p_kind:kind,p_action:action});setAvailable(old=>old.map(v=>v.kind===kind?{...v,[action==='announcement'?'announcement_seen':action]:true}:v));};
 async function open(kind){setError('');const {data,error}=await supabase.rpc('fds_wrapped_get',{p_kind:kind});if(error){setError(error.message);return;}setPayload(data);setAnnounce(null);await mark(kind,'announcement');await mark(kind,'opened');}
 function close(completed=false){if(completed&&payload)mark(payload.kind,'completed');setPayload(null);}
 if(!user||loadedFor!==user.id||!available.length)return null;
 return <>{showEntry&&<section className="wrapped-entry" aria-label="FDS Wrapped"><div><span>💜 FDS WRAPPED</span><h2>{available.some(v=>v.kind==='final')?'O teu FDS em números.':'O teu Dia 1 já está pronto.'}</h2></div><div className="wrapped-entry-actions">{available.map(v=><button key={v.kind} onClick={()=>open(v.kind)}>{v.kind==='final'?'VER FINAL':'VER DIA 1'} →</button>)}</div></section>}{error&&<p role="alert" className="wrapped-error">{error}</p>}{announce&&!payload&&<div className="wrapped-announcement" role="dialog" aria-modal="true" aria-label="Novo FDS Wrapped"><div><span>🔥 NOVA TIPS</span><h2>O TEU FDS WRAPPED ESTÁ PRONTO</h2><p>{announce==='day1'?'Vê como correu… antes da última noite.':'Acabou. Agora vê o teu FDS em números.'}</p><button onClick={()=>open(announce)}>VER AGORA →</button><button className="wrapped-later" onClick={()=>{mark(announce,'announcement');setAnnounce(null);}}>MAIS TARDE</button></div></div>}{payload&&<WrappedViewer payload={payload} onClose={close} onNavigate={onNavigate}/>}</>;
}
